spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
      # Make sure to disable spring.jpa.hibernate.ddl-auto if you use schema.sql.
      # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
    show-sql: true # 실행 되는 SQL문을 보여 줄지 설정
    properties:
      hibernate:
        format_sql: true # 형식화된 sql 문을 보여준다.
  h2:
    console:
      enabled: true
      path: /h2-console
      # localhost:8080/h2-console
      # JDBC URL : jdbc:h2:mem:testdb

---
spring:
  profiles: dev

---
spring:
  profiles: real